---
title: "Research"
---

<u><h2>Dimension Reduction </h2></u>
<h3>Preprints in review</h3>
<ol>
<li> Soale, A.N and Dong, Y. On Expectile-Assisted Inverse Regression
Estimation for Sufficient Dimension Reduction. <i>Submitted</i>. [download](https://arxiv.org/pdf/1910.10898.pdf)

<li> Soale, A.N. and Dong, Y. On Sufficient Dimension Reduction via Principal
Asymmetric Least Squares. <i> Submitted</i> [download](https://arxiv.org/pdf/2002.05264.pdf)
</ol>

<h3>In progress</h3>
<ol>
<li> Power, D. M., Soale, A. N., and Dong, Y. A Review of Moment-Based Sufficient Dimension Reduction Methods for Multivariate Response.

<li> Soale, A.N. and Tsyawo, E. Clustered Covariate Regression. <i>Working Paper. </i> [download](https://papers.ssrn.com/sol3/papers.cfm?abstract\_id=3394012)

<li> Soale, A.N. and Dong, Y. Robust Discrimination in Non-Gaussian Settings via Envelope Parameterization.

</ol>


<u><h2>Causal Inference </h2></u>
<h3>In progress</h3>
<ol>
<li> Soale, A.N., Forastiere, L., and E.M. Airoldi. Adjusting for Homophily in Estimating Spillover Effect in Social Networks.
</ol>


<u><h2>Text Analysis </h2></u>
<h3>Preprints in review</h3>
<ol>
<li> Janmohamed, K., Soale, A.N., Forastiere, L., Tang, W., Sha, Y., Massey, D., Demant, J., E.M. Airoldi, Kumar, N. The Online Vaping Narrative and its Intersection with Covid-19: Initial Study Using Topic Modeling Techniques. Journal of Medical Internet Research. [To appear](https://preprints.jmir.org/preprint/21743/accepted)

<li> Kumar, N., Soale, A.N., Janmohamed, K., Sha, Y., Forastiere L., E.M. Airoldi. Global Pandemic May Reduce Levels of Online Misinformation: The Case Of E-Cigarettes. Submitted.
</ol>

